### ISSUE TITLE
Filter giphy image by rating

### ISSUE THREAD

**Issue by swegner** [alexisbernard/teamodoro#2]
teamodoro is awesome. I use it at work every day. I'm getting the rest of my team to use it.

But sometimes the gifs that it shows are probably not-so-appropriate for the workplace.

It'd be nice to be able to avoid some of these less-suitable-for-work images. Some ideas:

* Use the ["rating" filter on the giphy API](https://github.com/Giphy/GiphyAPI#random-endpoint). Perhaps make this configurable on the client.
* Allow the user to "next" a particular image to get rid of it, and potentially blacklist it.

**Comment by alexisbernard** [comment]
I tried to play with the rating parameter but it doesn't seem to be very accurate. Anyway I set it to g and we will see how it goes :)

I prefer to avoid blacklist to keep the code base very simple (no options, no database, ...).

**Comment by swegner** [comment]
Nice, thanks!
